# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Author:   Manuel Villa
# Task:     Compute crime rates and crime rate changes in each CA county
# Sources:  California DOJ Open Justice Initiative; U.S. Census
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


# 1. SOURCE DATA ==================================================

# 1.1. Import -----

# Population data 
# Output data generated by script "population_county_level.R"
df_population <- read.csv('output_data/population_1980_2017_census_ca_counties.csv', header = TRUE, sep = ',')

# Crime data
# browseURL('https://openjustice.doj.ca.gov/downloads/Crimes_and_Clearances_with_Arson-1985-2017.csv')
df_ca_doj <- read.csv("source_data/crime/Crimes_and_Clearances_with_Arson-1985-2017.csv", header = TRUE, sep = ',')


# 1.2. Cleaning -----

  # 1.2.1. Population

# Filter out population data from 1980-1984 (We have no crime data for those years)
df_population <- filter(df_population, YEAR >= 1985)

  # 1.2.2. Crime

# Standardize column names
names(df_ca_doj) <- gsub('Sum', 'sum', names(df_ca_doj))

# Note 1:
# Colums represent number of crimes, but not all their values are >= 0.
# Most are small negatives; the greatest negative is -33.  According to a response by the CA DOJ, negative
# values appear when agencies “unfound” previously reported crimes. Details are in the response email, but
# the important matter is that they are not mistakes; they are supposed to be negative.

# Note 2:
# In 1 Januray 2013, the FBI broadened its definition of rape.
# Rape data from that year therefore became incomparable with previous data. 
# We decided to strip all the rape data from the calculation of violent and total crimes rates.
# browseURL('https://ucr.fbi.gov/crime-in-the-u.s/2013/crime-in-the-u.s.-2013/violent-crime/rape/rapemain_final.pdf')
df_ca_doj <- mutate(df_ca_doj, Violent_nr_sum = Homicide_sum + Robbery_sum + AggAssault_sum)
df_ca_doj <- mutate(df_ca_doj, TotalCrime_sum = Violent_nr_sum + Property_sum)



# 2. CREATE STATE-LEVEL & COUNTY-LEVEL CRIME DATAFRAMES =============================================

# 2.1. County level -----

# Crime data is broken down to city level; we need to aggregate it to county level
df_ca_counties <- select(df_ca_doj, County, Year, ends_with('sum'))
df_ca_counties <- group_by(df_ca_counties, County, Year)
df_ca_counties <- summarise_at(df_ca_counties, 
                               vars(ends_with('sum')), 
                               funs(sum))
df_ca_counties <- arrange(df_ca_counties, County, Year)


# Consistency test
stopifnot(nrow(df_ca_counties) == 58*33)

# We will join both dataframes using county & year as the joining fields, so need to
# transform them from factors to characters
df_ca_counties$County <- as.character(df_ca_counties$County)
df_population$COUNTY <- as.character(df_population$COUNTY)

# Join the population and crime dataframes
df_ca_counties <- left_join(df_ca_counties, df_population, by=c("Year"="YEAR", "County"="COUNTY"))


# 2.2. State level -----

# Aggregate across counties to create a second, state-level dataframe.
df_ca_state <- group_by(ungroup(df_ca_counties), Year)
df_ca_state <- summarise_at(df_ca_state, 
                            vars(ends_with('sum'), TOTAL_POP), 
                            funs(sum))
df_ca_state <- ungroup(df_ca_state)

# Consistency test
stopifnot(nrow(df_ca_state) == 33)

rm(df_population, df_ca_doj)



# 3. CALCULATE CRIME RATES ===================================

# 3.1. By County -----

# First, compute the annual changes in number of crimes
df_ca_counties <- mutate_at(df_ca_counties, 
                            vars(ends_with('sum')), 
                            funs(chg = . - lag(., 1)))
# Calculate the crime rates (# crimes per 100k people)
df_ca_counties <- mutate_at(df_ca_counties, 
                            vars(ends_with('sum')), 
                            funs(rate = ./TOTAL_POP*100e3))
# Fix column names
names(df_ca_counties) <- gsub('sum_rate', 'rate', names(df_ca_counties))

# Now, compute the changes in annual crime rates
df_ca_counties <- mutate_at(df_ca_counties, 
                            vars(ends_with('rate')), 
                            funs(chg = . - lag(.,1)))
df_ca_counties <- ungroup(df_ca_counties)


#  3.2. At state level -----

# First, compute the changes in annual number of crimes
df_ca_state <- mutate_at(df_ca_state, 
                         vars(ends_with('sum')), 
                         funs(chg = . - lag(., 1)))
# Calculate the crime rates (# crimes per 100,000 people)
df_ca_state <- mutate_at(df_ca_state, 
                         vars(ends_with('sum')), 
                         funs(rate = ./TOTAL_POP*100e3))
# Fix column names
names(df_ca_state) <- gsub('sum_rate', 'rate', names(df_ca_state))

# Calculate the annual change in crime rates
df_ca_state <- mutate_at(df_ca_state, 
                         vars(ends_with('rate')), 
                         funs(chg = . - lag(.,1)))



# 4. CONSISTENCY TESTS ==================================================

# 4.1. Dimensions -----

# Confirm the number of rows for the different dataframes are consistent
# with the fact that we have 32 years (1985-2016), 58 counties and one state.
stopifnot(nrow(df_ca_counties) == 58 *33)
stopifnot(nrow(df_ca_state) == 33)

# 4.2. Signs -----

# Are all crime numbers non-negative? (For da_ca_counties, there are some valid negatives)
stopifnot(!all(select(df_ca_counties, ends_with('sum')) >= 0, na.rm = TRUE))
stopifnot(all(select(df_ca_state, ends_with('sum')) >= 0, na.rm = TRUE))

# Are crime and rate changes both positive and negative?
stopifnot(!all(select(df_ca_state, ends_with('chg')) >= 0, na.rm = TRUE))
stopifnot(!all(select(df_ca_state, ends_with('chg')) <  0, na.rm = TRUE))

stopifnot(!all(select(df_ca_counties, ends_with('chg')) >= 0, na.rm = TRUE))
stopifnot(!all(select(df_ca_counties, ends_with('chg')) <  0, na.rm = TRUE))


# 4.3. Minimums and Maximum -----

# Maximum & minimum annual number of crimes
min(select(df_ca_state, ends_with('sum')), na.rm = TRUE)
max(select(df_ca_state, ends_with('sum')), na.rm = TRUE) # 2,048,133: Total number of crimes in CA in 1992

min(select(df_ca_counties, ends_with('sum')), na.rm = TRUE)
max(select(df_ca_counties, ends_with('sum')), na.rm = TRUE) # 685,581: Total number of crimes in L.A. County, 1991

# Maximum & minimum changes in annual number of crimes
min(select(df_ca_state, ends_with('chg')), na.rm = TRUE) # -183,159: Drop of total criimes in CA, 1996
max(select(df_ca_state, ends_with('chg')), na.rm = TRUE) # 102,971: Increase in total criimes in CA, 1986

min(select(df_ca_counties, ends_with('chg')), na.rm = TRUE) # -59,625 (Consistently smaller drop than -183,159)
max(select(df_ca_counties, ends_with('chg')), na.rm = TRUE) # 57,604 (Conistently smaller increase than 102,971)


# 4.4. Other tests ------

# Confirm that the year 1985 contains only NA values in the columns that calculate annual changes.
stopifnot(all(is.na(df_ca_state[df_ca_state$Year == 1985, grepl('chg', names(df_ca_state))])))
stopifnot(all(is.na(df_ca_counties[df_ca_counties$Year == 1985, grepl('chg', names(df_ca_counties))])))



# 5. EXPORT DATA =======================================================

write.csv(df_ca_state, 'output_data/crime_rates_1985_2017_doj_ca_state.csv', row.names = FALSE)
write.csv(df_ca_counties, 'output_data/crime_rates_1985_2017_doj_ca_counties.csv', row.names = FALSE)
